use magick_rust;
use std::str::FromStr;

#[derive(PartialEq,Eq,Debug,Fail)]
#[fail(display = "Unknown composition operator: {}", _0)]
pub struct UnknownCompositeOperator(String);

#[derive(PartialEq,Eq,Debug,Copy,Clone)]
pub enum CompositeOperator {
    Undefined,
    Alpha,
    Atop,
    Blend,
    Blur,
    Bumpmap,
    ChangeMask,
    Clear,
    ColorBurn,
    ColorDodge,
    Colorize,
    CopyBlack,
    CopyBlue,
    Copy,
    CopyCyan,
    CopyGreen,
    CopyMagenta,
    CopyAlpha,
    CopyRed,
    CopyYellow,
    Darken,
    DarkenIntensity,
    Difference,
    Displace,
    Dissolve,
    Distort,
    DivideDst,
    DivideSrc,
    DstAtop,
    Dst,
    DstIn,
    DstOut,
    DstOver,
    Exclusion,
    HardLight,
    HardMix,
    Hue,
    In,
    Intensity,
    Lighten,
    LightenIntensity,
    LinearBurn,
    LinearDodge,
    LinearLight,
    Luminize,
    Mathematics,
    MinusDst,
    MinusSrc,
    Modulate,
    ModulusAdd,
    ModulusSubtract,
    Multiply,
    No,
    Out,
    Over,
    Overlay,
    PegtopLight,
    PinLight,
    Plus,
    Replace,
    Saturate,
    Screen,
    SoftLight,
    SrcAtop,
    Src,
    SrcIn,
    SrcOut,
    SrcOver,
    Threshold,
    VividLight,
    Xor,
    Stereo,
}

impl FromStr for CompositeOperator {
    type Err = UnknownCompositeOperator;
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        Ok(match input {
            "undefined" => CompositeOperator::Undefined,
            "alpha" => CompositeOperator::Alpha,
            "atop" => CompositeOperator::Atop,
            "blend" => CompositeOperator::Blend,
            "blur" => CompositeOperator::Blur,
            "bumpmap" => CompositeOperator::Bumpmap,
            "change_mask" => CompositeOperator::ChangeMask,
            "clear" => CompositeOperator::Clear,
            "color_burn" => CompositeOperator::ColorBurn,
            "color_dodge" => CompositeOperator::ColorDodge,
            "colorize" => CompositeOperator::Colorize,
            "copy_black" => CompositeOperator::CopyBlack,
            "copy_blue" => CompositeOperator::CopyBlue,
            "copy" => CompositeOperator::Copy,
            "copy_cyan" => CompositeOperator::CopyCyan,
            "copy_green" => CompositeOperator::CopyGreen,
            "copy_magenta" => CompositeOperator::CopyMagenta,
            "copy_alpha" => CompositeOperator::CopyAlpha,
            "copy_red" => CompositeOperator::CopyRed,
            "copy_yellow" => CompositeOperator::CopyYellow,
            "darken" => CompositeOperator::Darken,
            "darken_intensity" => CompositeOperator::DarkenIntensity,
            "difference" => CompositeOperator::Difference,
            "displace" => CompositeOperator::Displace,
            "dissolve" => CompositeOperator::Dissolve,
            "distort" => CompositeOperator::Distort,
            "divide_dst" => CompositeOperator::DivideDst,
            "divide_src" => CompositeOperator::DivideSrc,
            "dst_atop" => CompositeOperator::DstAtop,
            "dst" => CompositeOperator::Dst,
            "dst_in" => CompositeOperator::DstIn,
            "dst_out" => CompositeOperator::DstOut,
            "dst_over" => CompositeOperator::DstOver,
            "exclusion" => CompositeOperator::Exclusion,
            "hard_light" => CompositeOperator::HardLight,
            "hard_mix" => CompositeOperator::HardMix,
            "hue" => CompositeOperator::Hue,
            "in" => CompositeOperator::In,
            "intensity" => CompositeOperator::Intensity,
            "lighten" => CompositeOperator::Lighten,
            "lighten_intensity" => CompositeOperator::LightenIntensity,
            "linear_burn" => CompositeOperator::LinearBurn,
            "linear_dodge" => CompositeOperator::LinearDodge,
            "linear_light" => CompositeOperator::LinearLight,
            "luminize" => CompositeOperator::Luminize,
            "mathematics" => CompositeOperator::Mathematics,
            "minus_dst" => CompositeOperator::MinusDst,
            "minus_src" => CompositeOperator::MinusSrc,
            "modulate" => CompositeOperator::Modulate,
            "modulus_add" => CompositeOperator::ModulusAdd,
            "modulus_subtract" => CompositeOperator::ModulusSubtract,
            "multiply" => CompositeOperator::Multiply,
            "no" => CompositeOperator::No,
            "out" => CompositeOperator::Out,
            "over" => CompositeOperator::Over,
            "overlay" => CompositeOperator::Overlay,
            "pegtop_light" => CompositeOperator::PegtopLight,
            "pin_light" => CompositeOperator::PinLight,
            "plus" => CompositeOperator::Plus,
            "replace" => CompositeOperator::Replace,
            "saturate" => CompositeOperator::Saturate,
            "screen" => CompositeOperator::Screen,
            "soft_light" => CompositeOperator::SoftLight,
            "src_atop" => CompositeOperator::SrcAtop,
            "src" => CompositeOperator::Src,
            "src_in" => CompositeOperator::SrcIn,
            "src_out" => CompositeOperator::SrcOut,
            "src_over" => CompositeOperator::SrcOver,
            "threshold" => CompositeOperator::Threshold,
            "vivid_light" => CompositeOperator::VividLight,
            "xor" => CompositeOperator::Xor,
            "stereo" => CompositeOperator::Stereo,
            _ => return Err(UnknownCompositeOperator(input.to_owned()))
        })
    }
}

impl From<CompositeOperator> for magick_rust::CompositeOperator {
    fn from(from: CompositeOperator) -> magick_rust::CompositeOperator {
        match from {
            CompositeOperator::Undefined => magick_rust::CompositeOperator::UndefinedCompositeOp,
            CompositeOperator::Alpha => magick_rust::CompositeOperator::AlphaCompositeOp,
            CompositeOperator::Atop => magick_rust::CompositeOperator::AtopCompositeOp,
            CompositeOperator::Blend => magick_rust::CompositeOperator::BlendCompositeOp,
            CompositeOperator::Blur => magick_rust::CompositeOperator::BlurCompositeOp,
            CompositeOperator::Bumpmap => magick_rust::CompositeOperator::BumpmapCompositeOp,
            CompositeOperator::ChangeMask => magick_rust::CompositeOperator::ChangeMaskCompositeOp,
            CompositeOperator::Clear => magick_rust::CompositeOperator::ClearCompositeOp,
            CompositeOperator::ColorBurn => magick_rust::CompositeOperator::ColorBurnCompositeOp,
            CompositeOperator::ColorDodge => magick_rust::CompositeOperator::ColorDodgeCompositeOp,
            CompositeOperator::Colorize => magick_rust::CompositeOperator::ColorizeCompositeOp,
            CompositeOperator::CopyBlack => magick_rust::CompositeOperator::CopyBlackCompositeOp,
            CompositeOperator::CopyBlue => magick_rust::CompositeOperator::CopyBlueCompositeOp,
            CompositeOperator::Copy => magick_rust::CompositeOperator::CopyCompositeOp,
            CompositeOperator::CopyCyan => magick_rust::CompositeOperator::CopyCyanCompositeOp,
            CompositeOperator::CopyGreen => magick_rust::CompositeOperator::CopyGreenCompositeOp,
            CompositeOperator::CopyMagenta => magick_rust::CompositeOperator::CopyMagentaCompositeOp,
            CompositeOperator::CopyAlpha => magick_rust::CompositeOperator::CopyAlphaCompositeOp,
            CompositeOperator::CopyRed => magick_rust::CompositeOperator::CopyRedCompositeOp,
            CompositeOperator::CopyYellow => magick_rust::CompositeOperator::CopyYellowCompositeOp,
            CompositeOperator::Darken => magick_rust::CompositeOperator::DarkenCompositeOp,
            CompositeOperator::DarkenIntensity => magick_rust::CompositeOperator::DarkenIntensityCompositeOp,
            CompositeOperator::Difference => magick_rust::CompositeOperator::DifferenceCompositeOp,
            CompositeOperator::Displace => magick_rust::CompositeOperator::DisplaceCompositeOp,
            CompositeOperator::Dissolve => magick_rust::CompositeOperator::DissolveCompositeOp,
            CompositeOperator::Distort => magick_rust::CompositeOperator::DistortCompositeOp,
            CompositeOperator::DivideDst => magick_rust::CompositeOperator::DivideDstCompositeOp,
            CompositeOperator::DivideSrc => magick_rust::CompositeOperator::DivideSrcCompositeOp,
            CompositeOperator::DstAtop => magick_rust::CompositeOperator::DstAtopCompositeOp,
            CompositeOperator::Dst => magick_rust::CompositeOperator::DstCompositeOp,
            CompositeOperator::DstIn => magick_rust::CompositeOperator::DstInCompositeOp,
            CompositeOperator::DstOut => magick_rust::CompositeOperator::DstOutCompositeOp,
            CompositeOperator::DstOver => magick_rust::CompositeOperator::DstOverCompositeOp,
            CompositeOperator::Exclusion => magick_rust::CompositeOperator::ExclusionCompositeOp,
            CompositeOperator::HardLight => magick_rust::CompositeOperator::HardLightCompositeOp,
            CompositeOperator::HardMix => magick_rust::CompositeOperator::HardMixCompositeOp,
            CompositeOperator::Hue => magick_rust::CompositeOperator::HueCompositeOp,
            CompositeOperator::In => magick_rust::CompositeOperator::InCompositeOp,
            CompositeOperator::Intensity => magick_rust::CompositeOperator::IntensityCompositeOp,
            CompositeOperator::Lighten => magick_rust::CompositeOperator::LightenCompositeOp,
            CompositeOperator::LightenIntensity => magick_rust::CompositeOperator::LightenIntensityCompositeOp,
            CompositeOperator::LinearBurn => magick_rust::CompositeOperator::LinearBurnCompositeOp,
            CompositeOperator::LinearDodge => magick_rust::CompositeOperator::LinearDodgeCompositeOp,
            CompositeOperator::LinearLight => magick_rust::CompositeOperator::LinearLightCompositeOp,
            CompositeOperator::Luminize => magick_rust::CompositeOperator::LuminizeCompositeOp,
            CompositeOperator::Mathematics => magick_rust::CompositeOperator::MathematicsCompositeOp,
            CompositeOperator::MinusDst => magick_rust::CompositeOperator::MinusDstCompositeOp,
            CompositeOperator::MinusSrc => magick_rust::CompositeOperator::MinusSrcCompositeOp,
            CompositeOperator::Modulate => magick_rust::CompositeOperator::ModulateCompositeOp,
            CompositeOperator::ModulusAdd => magick_rust::CompositeOperator::ModulusAddCompositeOp,
            CompositeOperator::ModulusSubtract => magick_rust::CompositeOperator::ModulusSubtractCompositeOp,
            CompositeOperator::Multiply => magick_rust::CompositeOperator::MultiplyCompositeOp,
            CompositeOperator::No => magick_rust::CompositeOperator::NoCompositeOp,
            CompositeOperator::Out => magick_rust::CompositeOperator::OutCompositeOp,
            CompositeOperator::Over => magick_rust::CompositeOperator::OverCompositeOp,
            CompositeOperator::Overlay => magick_rust::CompositeOperator::OverlayCompositeOp,
            CompositeOperator::PegtopLight => magick_rust::CompositeOperator::PegtopLightCompositeOp,
            CompositeOperator::PinLight => magick_rust::CompositeOperator::PinLightCompositeOp,
            CompositeOperator::Plus => magick_rust::CompositeOperator::PlusCompositeOp,
            CompositeOperator::Replace => magick_rust::CompositeOperator::ReplaceCompositeOp,
            CompositeOperator::Saturate => magick_rust::CompositeOperator::SaturateCompositeOp,
            CompositeOperator::Screen => magick_rust::CompositeOperator::ScreenCompositeOp,
            CompositeOperator::SoftLight => magick_rust::CompositeOperator::SoftLightCompositeOp,
            CompositeOperator::SrcAtop => magick_rust::CompositeOperator::SrcAtopCompositeOp,
            CompositeOperator::Src => magick_rust::CompositeOperator::SrcCompositeOp,
            CompositeOperator::SrcIn => magick_rust::CompositeOperator::SrcInCompositeOp,
            CompositeOperator::SrcOut => magick_rust::CompositeOperator::SrcOutCompositeOp,
            CompositeOperator::SrcOver => magick_rust::CompositeOperator::SrcOverCompositeOp,
            CompositeOperator::Threshold => magick_rust::CompositeOperator::ThresholdCompositeOp,
            CompositeOperator::VividLight => magick_rust::CompositeOperator::VividLightCompositeOp,
            CompositeOperator::Xor => magick_rust::CompositeOperator::XorCompositeOp,
            CompositeOperator::Stereo => magick_rust::CompositeOperator::StereoCompositeOp,
        }
    }
}

impl From<magick_rust::CompositeOperator> for CompositeOperator {
    fn from(from: magick_rust::CompositeOperator) -> Self {
        match from {
            magick_rust::CompositeOperator::UndefinedCompositeOp => CompositeOperator::Undefined,
            magick_rust::CompositeOperator::AlphaCompositeOp => CompositeOperator::Alpha,
            magick_rust::CompositeOperator::AtopCompositeOp => CompositeOperator::Atop,
            magick_rust::CompositeOperator::BlendCompositeOp => CompositeOperator::Blend,
            magick_rust::CompositeOperator::BlurCompositeOp => CompositeOperator::Blur,
            magick_rust::CompositeOperator::BumpmapCompositeOp => CompositeOperator::Bumpmap,
            magick_rust::CompositeOperator::ChangeMaskCompositeOp => CompositeOperator::ChangeMask,
            magick_rust::CompositeOperator::ClearCompositeOp => CompositeOperator::Clear,
            magick_rust::CompositeOperator::ColorBurnCompositeOp => CompositeOperator::ColorBurn,
            magick_rust::CompositeOperator::ColorDodgeCompositeOp => CompositeOperator::ColorDodge,
            magick_rust::CompositeOperator::ColorizeCompositeOp => CompositeOperator::Colorize,
            magick_rust::CompositeOperator::CopyBlackCompositeOp => CompositeOperator::CopyBlack,
            magick_rust::CompositeOperator::CopyBlueCompositeOp => CompositeOperator::CopyBlue,
            magick_rust::CompositeOperator::CopyCompositeOp => CompositeOperator::Copy,
            magick_rust::CompositeOperator::CopyCyanCompositeOp => CompositeOperator::CopyCyan,
            magick_rust::CompositeOperator::CopyGreenCompositeOp => CompositeOperator::CopyGreen,
            magick_rust::CompositeOperator::CopyMagentaCompositeOp => CompositeOperator::CopyMagenta,
            magick_rust::CompositeOperator::CopyAlphaCompositeOp => CompositeOperator::CopyAlpha,
            magick_rust::CompositeOperator::CopyRedCompositeOp => CompositeOperator::CopyRed,
            magick_rust::CompositeOperator::CopyYellowCompositeOp => CompositeOperator::CopyYellow,
            magick_rust::CompositeOperator::DarkenCompositeOp => CompositeOperator::Darken,
            magick_rust::CompositeOperator::DarkenIntensityCompositeOp => CompositeOperator::DarkenIntensity,
            magick_rust::CompositeOperator::DifferenceCompositeOp => CompositeOperator::Difference,
            magick_rust::CompositeOperator::DisplaceCompositeOp => CompositeOperator::Displace,
            magick_rust::CompositeOperator::DissolveCompositeOp => CompositeOperator::Dissolve,
            magick_rust::CompositeOperator::DistortCompositeOp => CompositeOperator::Distort,
            magick_rust::CompositeOperator::DivideDstCompositeOp => CompositeOperator::DivideDst,
            magick_rust::CompositeOperator::DivideSrcCompositeOp => CompositeOperator::DivideSrc,
            magick_rust::CompositeOperator::DstAtopCompositeOp => CompositeOperator::DstAtop,
            magick_rust::CompositeOperator::DstCompositeOp => CompositeOperator::Dst,
            magick_rust::CompositeOperator::DstInCompositeOp => CompositeOperator::DstIn,
            magick_rust::CompositeOperator::DstOutCompositeOp => CompositeOperator::DstOut,
            magick_rust::CompositeOperator::DstOverCompositeOp => CompositeOperator::DstOver,
            magick_rust::CompositeOperator::ExclusionCompositeOp => CompositeOperator::Exclusion,
            magick_rust::CompositeOperator::HardLightCompositeOp => CompositeOperator::HardLight,
            magick_rust::CompositeOperator::HardMixCompositeOp => CompositeOperator::HardMix,
            magick_rust::CompositeOperator::HueCompositeOp => CompositeOperator::Hue,
            magick_rust::CompositeOperator::InCompositeOp => CompositeOperator::In,
            magick_rust::CompositeOperator::IntensityCompositeOp => CompositeOperator::Intensity,
            magick_rust::CompositeOperator::LightenCompositeOp => CompositeOperator::Lighten,
            magick_rust::CompositeOperator::LightenIntensityCompositeOp => CompositeOperator::LightenIntensity,
            magick_rust::CompositeOperator::LinearBurnCompositeOp => CompositeOperator::LinearBurn,
            magick_rust::CompositeOperator::LinearDodgeCompositeOp => CompositeOperator::LinearDodge,
            magick_rust::CompositeOperator::LinearLightCompositeOp => CompositeOperator::LinearLight,
            magick_rust::CompositeOperator::LuminizeCompositeOp => CompositeOperator::Luminize,
            magick_rust::CompositeOperator::MathematicsCompositeOp => CompositeOperator::Mathematics,
            magick_rust::CompositeOperator::MinusDstCompositeOp => CompositeOperator::MinusDst,
            magick_rust::CompositeOperator::MinusSrcCompositeOp => CompositeOperator::MinusSrc,
            magick_rust::CompositeOperator::ModulateCompositeOp => CompositeOperator::Modulate,
            magick_rust::CompositeOperator::ModulusAddCompositeOp => CompositeOperator::ModulusAdd,
            magick_rust::CompositeOperator::ModulusSubtractCompositeOp => CompositeOperator::ModulusSubtract,
            magick_rust::CompositeOperator::MultiplyCompositeOp => CompositeOperator::Multiply,
            magick_rust::CompositeOperator::NoCompositeOp => CompositeOperator::No,
            magick_rust::CompositeOperator::OutCompositeOp => CompositeOperator::Out,
            magick_rust::CompositeOperator::OverCompositeOp => CompositeOperator::Over,
            magick_rust::CompositeOperator::OverlayCompositeOp => CompositeOperator::Overlay,
            magick_rust::CompositeOperator::PegtopLightCompositeOp => CompositeOperator::PegtopLight,
            magick_rust::CompositeOperator::PinLightCompositeOp => CompositeOperator::PinLight,
            magick_rust::CompositeOperator::PlusCompositeOp => CompositeOperator::Plus,
            magick_rust::CompositeOperator::ReplaceCompositeOp => CompositeOperator::Replace,
            magick_rust::CompositeOperator::SaturateCompositeOp => CompositeOperator::Saturate,
            magick_rust::CompositeOperator::ScreenCompositeOp => CompositeOperator::Screen,
            magick_rust::CompositeOperator::SoftLightCompositeOp => CompositeOperator::SoftLight,
            magick_rust::CompositeOperator::SrcAtopCompositeOp => CompositeOperator::SrcAtop,
            magick_rust::CompositeOperator::SrcCompositeOp => CompositeOperator::Src,
            magick_rust::CompositeOperator::SrcInCompositeOp => CompositeOperator::SrcIn,
            magick_rust::CompositeOperator::SrcOutCompositeOp => CompositeOperator::SrcOut,
            magick_rust::CompositeOperator::SrcOverCompositeOp => CompositeOperator::SrcOver,
            magick_rust::CompositeOperator::ThresholdCompositeOp => CompositeOperator::Threshold,
            magick_rust::CompositeOperator::VividLightCompositeOp => CompositeOperator::VividLight,
            magick_rust::CompositeOperator::XorCompositeOp => CompositeOperator::Xor,
            magick_rust::CompositeOperator::StereoCompositeOp => CompositeOperator::Stereo,
        }
    }
}
